{% set name = "nzgeom" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nzgeom-{{ version }}.tar.gz
  sha256: d705e5da623873b365828df9d2f0afccb3a3de48d9f0a62c094e471772cb8163

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - geopandas
    - python >=3.10

test:
  imports:
    - nzgeom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Timothy-W-Hilton/NZ_geometries
  summary: provide geospatial geometry for NZ coastlines and administrative regions
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Timothy-W-Hilton
