{% set python_min = "3.9" %}
{% set name = "nzgeom" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nzgeom-{{ version }}.tar.gz
  sha256: d66ef3bdd6a14776d59842e353e714092e6e579e3c74563964de62aba65a7d2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - geopandas
    - python >={{ python_min }}

test:
  imports:
    - nzgeom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Timothy-W-Hilton/NZ_geometries
  summary: provide geospatial geometry for NZ coastlines and administrative regions
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Timothy-W-Hilton
